sudo: required
language: julia
notifications:
  email: false
before_install:
- apt-get install python-pip
- python --version
- pip --version
- pip install --upgrade pip
- pip install matplotlib
script:
- date
- julia -e 'include("test/runtests.jl");'
- julia -e 'include("benchmark/perftest.jl")'
after_success:
- ls -la benchmark/*.png
